# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: humans.proto

require 'google/protobuf'

require 'google/protobuf/empty'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "od.api.v1.humans.Human" do
    optional :id, :uint64, 1
    optional :email, :string, 2
  end
  add_message "od.api.v1.humans.GetHumanRequest" do
    optional :email, :string, 1
  end
end

module Od
  module Api
    module V1
      module Humans
        Human = Google::Protobuf::DescriptorPool.generated_pool.lookup("od.api.v1.humans.Human").msgclass
        GetHumanRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("od.api.v1.humans.GetHumanRequest").msgclass
      end
    end
  end
end
