#!/usr/bin/env python
import os
import re
import subprocess

root_dir = os.path.abspath(os.path.join(__file__, '../../..'))

protos_dir = os.path.join(root_dir, 'protos')
proto_files = [os.path.join(protos_dir, f) for f in os.listdir(protos_dir)
               if f.endswith('.proto')]

print('Compiling files: ', proto_files)

output_dir = os.path.join(root_dir, 'python/sesame_rpc/lib/pb')
print('Outputting to: ', output_dir)

python_sesame_rpc = os.path.join(root_dir, 'bin/python_sesame_rpc')

cmds = [
    'protoc', '-I' + protos_dir, '--python_out=' + output_dir,
    '--plugin=protoc-gen-odrpc=' + python_sesame_rpc,
    '--odrpc_out=' + output_dir]
cmds += compile_files

subprocess.call(cmds)
