# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: humans.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import fruits_pb2 as fruits__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='humans.proto',
  package='od.api.v1.humans',
  syntax='proto3',
  serialized_pb=_b('\n\x0chumans.proto\x12\x10od.api.v1.humans\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x66ruits.proto\"J\n\x05Human\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12&\n\x05\x61pple\x18\x03 \x01(\x0b\x32\x17.od.api.v1.fruits.Apple\" \n\x0fGetHumanRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t2\x93\x01\n\x0cHumanService\x12\x39\n\x04Info\x12\x16.google.protobuf.Empty\x1a\x17.od.api.v1.humans.Human\"\x00\x12H\n\x08GetHuman\x12!.od.api.v1.humans.GetHumanRequest\x1a\x17.od.api.v1.humans.Human\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,fruits__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HUMAN = _descriptor.Descriptor(
  name='Human',
  full_name='od.api.v1.humans.Human',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='od.api.v1.humans.Human.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='od.api.v1.humans.Human.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='apple', full_name='od.api.v1.humans.Human.apple', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=151,
)


_GETHUMANREQUEST = _descriptor.Descriptor(
  name='GetHumanRequest',
  full_name='od.api.v1.humans.GetHumanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='od.api.v1.humans.GetHumanRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=185,
)

_HUMAN.fields_by_name['apple'].message_type = fruits__pb2._APPLE
DESCRIPTOR.message_types_by_name['Human'] = _HUMAN
DESCRIPTOR.message_types_by_name['GetHumanRequest'] = _GETHUMANREQUEST

Human = _reflection.GeneratedProtocolMessageType('Human', (_message.Message,), dict(
  DESCRIPTOR = _HUMAN,
  __module__ = 'humans_pb2'
  # @@protoc_insertion_point(class_scope:od.api.v1.humans.Human)
  ))
_sym_db.RegisterMessage(Human)

GetHumanRequest = _reflection.GeneratedProtocolMessageType('GetHumanRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETHUMANREQUEST,
  __module__ = 'humans_pb2'
  # @@protoc_insertion_point(class_scope:od.api.v1.humans.GetHumanRequest)
  ))
_sym_db.RegisterMessage(GetHumanRequest)


# @@protoc_insertion_point(module_scope)
